.TH "src/internationalisation.h" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/internationalisation.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <libintl.h>\fP
.br
\fC#include <locale.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_\fP(string)   gettext(string)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _(string)   gettext(string)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
