.TH "src/main.cpp" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <list>\fP
.br
\fC#include 'internationalisation.h'\fP
.br
\fC#include 'vjassdoc.h'\fP
.br
\fC#include 'parser.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
