.TH "src/object.h" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/object.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <functional>\fP
.br
\fC#include 'parser.h'\fP
.br
\fC#include 'internationalisation.h'\fP
.br
\fC#include 'vjassdoc.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvjassdoc\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvjassdoc::Object\fP"
.br
.ti -1c
.RI "struct \fBvjassdoc::Object::AlphabeticalComparator\fP"
.br
.ti -1c
.RI "struct \fBvjassdoc::Object::IsInContainer\fP"
.br
.ti -1c
.RI "struct \fBvjassdoc::Object::IsInScope\fP"
.br
.ti -1c
.RI "struct \fBvjassdoc::Object::IsInLibrary\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
