.TH "todo" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBMember \fBvjassdoc::DocComment::init\fP() \fP" 1c
FIXME 
.PP
.PP
 
.IP "\fBMember \fBvjassdoc::File::File\fP(const std::string &filePath) \fP" 1c
Truncate the //! prefix 
.PP
.PP
 
.IP "\fBMember \fBvjassdoc::File::File\fP(const std::string &filePath) \fP" 1c
Just close if good? 
.PP
.PP
 
.IP "\fBMember \fBvjassdoc::Object::sqlTableHeader\fP(const std::string &tableName, const std::string &entries) \fP" 1c
This function should be used to distribute all table header creations to their classes. 
.PP
.PP
 
.IP "\fBMember \fBvjassdoc::Object::hasToSearchValueObject\fP(class Object *type, const std::string &expression) \fP" 1c
Code type == null?! 
.PP
.PP
 
.IP "\fBMember \fBvjassdoc::Parser::parse\fP() \fP" 1c
Test. 
.PP

