.TH "vjassdoc::SourceFile" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::SourceFile \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sourcefile.h>\fP
.PP
Inherits \fBvjassdoc::Object\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSourceFile\fP (const std::string &identifier, const std::string &path)"
.br
.ti -1c
.RI "\fBSourceFile\fP (std::vector< const unsigned char * > &columnVector)"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()"
.br
.ti -1c
.RI "virtual void \fBpageNavigation\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual void \fBpage\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual std::string \fBsqlStatement\fP () const "
.br
.ti -1c
.RI "std::string \fBpath\fP () const "
.br
.ti -1c
.RI "std::string \fBlineLink\fP (const unsigned int &line, const std::string &text) const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBsourceFileLineLink\fP (const class \fBObject\fP *object, const bool &sourceFileName=true, const std::string &identifier='-')"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vjassdoc::SourceFile::SourceFile (const std::string & identifier, const std::string & path)"
.PP
.SS "vjassdoc::SourceFile::SourceFile (std::vector< const unsigned char * > & columnVector)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void vjassdoc::SourceFile::init ()\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.SS "void vjassdoc::SourceFile::pageNavigation (std::ofstream & file) const\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.SS "void vjassdoc::SourceFile::page (std::ofstream & file) const\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.SS "std::string vjassdoc::SourceFile::sqlStatement () const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Object\fP.
.SS "std::string vjassdoc::SourceFile::path () const\fC [inline]\fP"
.PP
.SS "std::string vjassdoc::SourceFile::lineLink (const unsigned int & line, const std::string & text) const\fC [inline]\fP"
.PP
.SS "std::string vjassdoc::SourceFile::sourceFileLineLink (const class \fBObject\fP * object, const bool & sourceFileName = \fCtrue\fP, const std::string & identifier = \fC'-'\fP)\fC [inline, static]\fP"
.PP
\fBParameters:\fP
.RS 4
\fIsourceFileName\fP If this value is true, the name of source file will be shown as link. Otherwise the line will be shown. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
