.TH "vjassdoc::Scope" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::Scope \- 
.SH SYNOPSIS
.br
.PP
\fC#include <scope.h>\fP
.PP
Inherits \fBvjassdoc::Object\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScope\fP (const std::string &identifier, class \fBSourceFile\fP *sourceFile, unsigned int line, class \fBDocComment\fP *docComment, class \fBLibrary\fP *library, bool isPrivate, const std::string initializerExpression)"
.br
.ti -1c
.RI "\fBScope\fP (std::vector< const unsigned char * > &columnVector)"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()"
.br
.ti -1c
.RI "virtual void \fBpageNavigation\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual void \fBpage\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual std::string \fBsqlStatement\fP () const "
.br
.ti -1c
.RI "virtual class \fBLibrary\fP * \fBlibrary\fP () const "
.br
.ti -1c
.RI "bool \fBisPrivate\fP () const "
.br
.ti -1c
.RI "class \fBFunction\fP * \fBinitializer\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vjassdoc::Scope::Scope (const std::string & identifier, class \fBSourceFile\fP * sourceFile, unsigned int line, class \fBDocComment\fP * docComment, class \fBLibrary\fP * library, bool isPrivate, const std::string initializerExpression)"
.PP
.SS "vjassdoc::Scope::Scope (std::vector< const unsigned char * > & columnVector)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void vjassdoc::Scope::init ()\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.SS "void vjassdoc::Scope::pageNavigation (std::ofstream & file) const\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.SS "void vjassdoc::Scope::page (std::ofstream & file) const\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.SS "std::string vjassdoc::Scope::sqlStatement () const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Object\fP.
.SS "class \fBLibrary\fP * vjassdoc::Scope::library () const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Object\fP.
.SS "bool vjassdoc::Scope::isPrivate () const\fC [inline]\fP"
.PP
.SS "class \fBFunction\fP * vjassdoc::Scope::initializer () const\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
