.TH "src/vjassdoc.h" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/vjassdoc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <list>\fP
.br
\fC#include 'parser.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvjassdoc\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvjassdoc::Vjassdoc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
