.TH "vjassdoc::Object::AlphabeticalComparator" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::Object::AlphabeticalComparator \- 
.SH SYNOPSIS
.br
.PP
\fC#include <object.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const class \fBObject\fP *first, const class \fBObject\fP *second) const "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool vjassdoc::Object::AlphabeticalComparator::operator() (const class \fBObject\fP * first, const class \fBObject\fP * second) const\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
