.TH "vjassdoc::Parser::Comparator" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::Parser::Comparator \- 
.SH SYNOPSIS
.br
.PP
\fC#include <parser.h>\fP
.PP
Inherited by \fBvjassdoc::Object::IsInContainer\fP, \fBvjassdoc::Object::IsInLibrary\fP, \fBvjassdoc::Object::IsInScope\fP, and \fBvjassdoc::Struct::HasExtension\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBoperator()\fP (const class \fBObject\fP *thisObject, const class \fBObject\fP *otherObject) const "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool vjassdoc::Parser::Comparator::operator() (const class \fBObject\fP * thisObject, const class \fBObject\fP * otherObject) const\fC [virtual]\fP"
.PP
Reimplemented in \fBvjassdoc::Object::IsInContainer\fP, \fBvjassdoc::Object::IsInScope\fP, \fBvjassdoc::Object::IsInLibrary\fP, and \fBvjassdoc::Struct::HasExtension\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
