.TH "vjassdoc::Struct::HasExtension" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::Struct::HasExtension \- 
.SH SYNOPSIS
.br
.PP
\fC#include <struct.h>\fP
.PP
Inherits \fBvjassdoc::Parser::Comparator\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBoperator()\fP (const class \fBObject\fP *thisObject, const class \fBObject\fP *extension) const "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool vjassdoc::Struct::HasExtension::operator() (const class \fBObject\fP * thisObject, const class \fBObject\fP * extension) const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Parser::Comparator\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
