.TH "vjassdoc::Library" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::Library \- 
.SH SYNOPSIS
.br
.PP
\fC#include <library.h>\fP
.PP
Inherits \fBvjassdoc::Object\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLibrary\fP (const std::string &identifier, class \fBSourceFile\fP *sourceFile, unsigned int line, class \fBDocComment\fP *docComment, bool isOnce, const std::string &initializerExpression, std::list< std::string > *requirementExpressions)"
.br
.ti -1c
.RI "\fBLibrary\fP (std::vector< const unsigned char * > &columnVector)"
.br
.ti -1c
.RI "virtual \fB~Library\fP ()"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()"
.br
.ti -1c
.RI "virtual void \fBpageNavigation\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual void \fBpage\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual std::string \fBsqlStatement\fP () const "
.br
.ti -1c
.RI "bool \fBisOnce\fP () const "
.br
.ti -1c
.RI "class \fBFunction\fP * \fBinitializer\fP () const "
.br
.ti -1c
.RI "std::list< class \fBLibrary\fP * > * \fBrequirement\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vjassdoc::Library::Library (const std::string & identifier, class \fBSourceFile\fP * sourceFile, unsigned int line, class \fBDocComment\fP * docComment, bool isOnce, const std::string & initializerExpression, std::list< std::string > * requirementExpressions)"
.PP
.SS "vjassdoc::Library::Library (std::vector< const unsigned char * > & columnVector)"
.PP
.SS "vjassdoc::Library::~Library ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void vjassdoc::Library::init ()\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.SS "void vjassdoc::Library::pageNavigation (std::ofstream & file) const\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.SS "void vjassdoc::Library::page (std::ofstream & file) const\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.SS "std::string vjassdoc::Library::sqlStatement () const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Object\fP.
.SS "bool vjassdoc::Library::isOnce () const\fC [inline]\fP"
.PP
.SS "class \fBFunction\fP * vjassdoc::Library::initializer () const\fC [inline]\fP"
.PP
.SS "std::list< class \fBLibrary\fP * > * vjassdoc::Library::requirement () const\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
