.TH "vjassdoc::Method" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::Method \- 
.SH SYNOPSIS
.br
.PP
\fC#include <method.h>\fP
.PP
Inherits \fBvjassdoc::Function\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMethod\fP (const std::string &identifier, class \fBSourceFile\fP *sourceFile, unsigned int line, class \fBDocComment\fP *docComment, class \fBLibrary\fP *library, class \fBScope\fP *scope, bool isPrivate, std::list< std::string > *parameterTypeExpressions, std::list< std::string > *parameters, const std::string &returnTypeExpression, bool isPublic, bool isConstant, class \fBObject\fP *container, bool isStatic, bool isStub, const std::string &defaultReturnValueExpression)"
.br
.RI "\fIisNative always is false. \fP"
.ti -1c
.RI "\fBMethod\fP (std::vector< const unsigned char * > &columnVector)"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()"
.br
.ti -1c
.RI "virtual void \fBpageNavigation\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual void \fBpage\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual std::string \fBsqlStatement\fP () const "
.br
.ti -1c
.RI "virtual class \fBObject\fP * \fBcontainer\fP () const "
.br
.ti -1c
.RI "bool \fBisStatic\fP () const "
.br
.ti -1c
.RI "bool \fBisStub\fP () const "
.br
.ti -1c
.RI "class \fBObject\fP * \fBdefaultReturnValue\fP () const "
.br
.ti -1c
.RI "std::string \fBdefaultReturnValueExpression\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vjassdoc::Method::Method (const std::string & identifier, class \fBSourceFile\fP * sourceFile, unsigned int line, class \fBDocComment\fP * docComment, class \fBLibrary\fP * library, class \fBScope\fP * scope, bool isPrivate, std::list< std::string > * parameterTypeExpressions, std::list< std::string > * parameters, const std::string & returnTypeExpression, bool isPublic, bool isConstant, class \fBObject\fP * container, bool isStatic, bool isStub, const std::string & defaultReturnValueExpression)"
.PP
isNative always is false. 
.PP
.SS "vjassdoc::Method::Method (std::vector< const unsigned char * > & columnVector)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void vjassdoc::Method::init ()\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Function\fP.
.SS "void vjassdoc::Method::pageNavigation (std::ofstream & file) const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Function\fP.
.SS "void vjassdoc::Method::page (std::ofstream & file) const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Function\fP.
.SS "std::string vjassdoc::Method::sqlStatement () const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Function\fP.
.SS "class \fBObject\fP * vjassdoc::Method::container () const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Object\fP.
.SS "bool vjassdoc::Method::isStatic () const\fC [inline]\fP"
.PP
.SS "bool vjassdoc::Method::isStub () const\fC [inline]\fP"
.PP
.SS "class \fBObject\fP * vjassdoc::Method::defaultReturnValue () const\fC [inline]\fP"
.PP
.SS "std::string vjassdoc::Method::defaultReturnValueExpression () const\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
