.TH "vjassdoc::Comment" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::Comment \- 
.SH SYNOPSIS
.br
.PP
\fC#include <comment.h>\fP
.PP
Inherits \fBvjassdoc::Object\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComment\fP (const std::string &identifier, class \fBSourceFile\fP *sourceFile, unsigned int line, class \fBDocComment\fP *docComment)"
.br
.ti -1c
.RI "\fBComment\fP (std::vector< const unsigned char * > &columnVector)"
.br
.ti -1c
.RI "virtual \fB~Comment\fP ()"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()"
.br
.ti -1c
.RI "virtual void \fBpageNavigation\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual void \fBpage\fP (std::ofstream &file) const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vjassdoc::Comment::Comment (const std::string & identifier, class \fBSourceFile\fP * sourceFile, unsigned int line, class \fBDocComment\fP * docComment)"
.PP
.SS "vjassdoc::Comment::Comment (std::vector< const unsigned char * > & columnVector)"
.PP
.SS "vjassdoc::Comment::~Comment ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void vjassdoc::Comment::init ()\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.SS "void vjassdoc::Comment::pageNavigation (std::ofstream & file) const\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.SS "void vjassdoc::Comment::page (std::ofstream & file) const\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
