.TH "vjassdoc::Member" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::Member \- 
.SH SYNOPSIS
.br
.PP
\fC#include <member.h>\fP
.PP
Inherits \fBvjassdoc::Global\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMember\fP (const std::string &identifier, class \fBSourceFile\fP *sourceFile, unsigned int line, class \fBDocComment\fP *docComment, class \fBLibrary\fP *library, class \fBScope\fP *scope, bool isPrivate, bool isPublic, bool isConstant, const std::string &typeExpression, const std::string &valueExpression, const std::string &sizeExpression, class \fBObject\fP *container, bool isStatic, bool isDelegate)"
.br
.ti -1c
.RI "\fBMember\fP (std::vector< const unsigned char * > &columnVector)"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()"
.br
.ti -1c
.RI "virtual void \fBpageNavigation\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual void \fBpage\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual std::string \fBsqlStatement\fP () const "
.br
.ti -1c
.RI "virtual class \fBObject\fP * \fBcontainer\fP () const "
.br
.ti -1c
.RI "bool \fBisStatic\fP () const "
.br
.ti -1c
.RI "bool \fBisDelegate\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vjassdoc::Member::Member (const std::string & identifier, class \fBSourceFile\fP * sourceFile, unsigned int line, class \fBDocComment\fP * docComment, class \fBLibrary\fP * library, class \fBScope\fP * scope, bool isPrivate, bool isPublic, bool isConstant, const std::string & typeExpression, const std::string & valueExpression, const std::string & sizeExpression, class \fBObject\fP * container, bool isStatic, bool isDelegate)"
.PP
.SS "vjassdoc::Member::Member (std::vector< const unsigned char * > & columnVector)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void vjassdoc::Member::init ()\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Global\fP.
.SS "void vjassdoc::Member::pageNavigation (std::ofstream & file) const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Global\fP.
.SS "void vjassdoc::Member::page (std::ofstream & file) const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Global\fP.
.SS "std::string vjassdoc::Member::sqlStatement () const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Global\fP.
.SS "class \fBObject\fP * vjassdoc::Member::container () const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Object\fP.
.SS "bool vjassdoc::Member::isStatic () const\fC [inline]\fP"
.PP
.SS "bool vjassdoc::Member::isDelegate () const\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
