.TH "vjassdoc::Object" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::Object \- 
.SH SYNOPSIS
.br
.PP
\fC#include <object.h>\fP
.PP
Inherited by \fBvjassdoc::Comment\fP, \fBvjassdoc::DocComment\fP, \fBvjassdoc::FunctionInterface\fP, \fBvjassdoc::Global\fP, \fBvjassdoc::Interface\fP, \fBvjassdoc::Keyword\fP, \fBvjassdoc::Library\fP, \fBvjassdoc::Scope\fP, \fBvjassdoc::SourceFile\fP, \fBvjassdoc::TextMacro\fP, and \fBvjassdoc::Type\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObject\fP (const std::string &identifier, class \fBSourceFile\fP *sourceFile, unsigned int line, class \fBDocComment\fP *docComment)"
.br
.ti -1c
.RI "\fBObject\fP (std::vector< const unsigned char * > &columnVector)"
.br
.ti -1c
.RI "virtual \fB~Object\fP ()"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBpageNavigation\fP (std::ofstream &file) const =0"
.br
.ti -1c
.RI "virtual void \fBpage\fP (std::ofstream &file) const =0"
.br
.ti -1c
.RI "std::string \fBpageLink\fP () const "
.br
.ti -1c
.RI "virtual std::string \fBsqlStatement\fP () const "
.br
.ti -1c
.RI "unsigned int \fBid\fP () const "
.br
.ti -1c
.RI "void \fBaddIdentifier\fP (const std::string &identifier)"
.br
.ti -1c
.RI "std::string \fBidentifier\fP () const "
.br
.ti -1c
.RI "class \fBSourceFile\fP * \fBsourceFile\fP () const "
.br
.ti -1c
.RI "unsigned int \fBline\fP () const "
.br
.ti -1c
.RI "class \fBDocComment\fP * \fBdocComment\fP () const "
.br
.ti -1c
.RI "virtual class \fBObject\fP * \fBcontainer\fP () const "
.br
.ti -1c
.RI "virtual class \fBScope\fP * \fBscope\fP () const "
.br
.ti -1c
.RI "virtual class \fBLibrary\fP * \fBlibrary\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBobjectPageLink\fP (const class \fBObject\fP *object, const std::string &identifier='-')"
.br
.ti -1c
.RI "static std::string \fBobjectLink\fP (const class \fBObject\fP *object, const std::string &identifier='-')"
.br
.ti -1c
.RI "static int \fBobjectId\fP (const class \fBObject\fP *object)"
.br
.ti -1c
.RI "static void \fBsetMaxIds\fP (int maxIds)"
.br
.ti -1c
.RI "static std::string \fBsqlFilteredString\fP (const std::string &usedString)"
.br
.ti -1c
.RI "static std::string \fBsqlTableHeader\fP (const std::string &tableName, const std::string &entries)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetIdentifier\fP (const std::string &identifier)"
.br
.ti -1c
.RI "std::string \fBanchor\fP () const "
.br
.ti -1c
.RI "class \fBObject\fP * \fBsearchObjectInList\fP (const std::string &identifier, const enum \fBParser::List\fP &list, enum \fBParser::SearchMode\fP searchMode=Parser::Unspecified)"
.br
.ti -1c
.RI "class \fBObject\fP * \fBfindValue\fP (class \fBObject\fP *type, std::string &valueExpression)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBhasToSearchValueObject\fP (class \fBObject\fP *type, const std::string &expression)"
.br
.ti -1c
.RI "static std::string \fBshowBooleanProperty\fP (const bool &property)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "class \fBObject\fP * \fBm_container\fP"
.br
.ti -1c
.RI "class \fBScope\fP * \fBm_scope\fP"
.br
.ti -1c
.RI "class \fBLibrary\fP * \fBm_library\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAlphabeticalComparator\fP"
.br
.ti -1c
.RI "struct \fBIsInContainer\fP"
.br
.ti -1c
.RI "struct \fBIsInLibrary\fP"
.br
.ti -1c
.RI "struct \fBIsInScope\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vjassdoc::Object::Object (const std::string & identifier, class \fBSourceFile\fP * sourceFile, unsigned int line, class \fBDocComment\fP * docComment)"
.PP
.SS "vjassdoc::Object::Object (std::vector< const unsigned char * > & columnVector)"
.PP
.SS "vjassdoc::Object::~Object ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "std::string vjassdoc::Object::objectPageLink (const class \fBObject\fP * object, const std::string & identifier = \fC'-'\fP)\fC [inline, static]\fP"
.PP
.SS "std::string vjassdoc::Object::objectLink (const class \fBObject\fP * object, const std::string & identifier = \fC'-'\fP)\fC [inline, static]\fP"
.PP
.SS "int vjassdoc::Object::objectId (const class \fBObject\fP * object)\fC [inline, static]\fP"
.PP
.SS "void vjassdoc::Object::setMaxIds (int maxIds)\fC [inline, static]\fP"
.PP
.SS "std::string vjassdoc::Object::sqlFilteredString (const std::string & usedString)\fC [static]\fP"
.PP
.SS "std::string vjassdoc::Object::sqlTableHeader (const std::string & tableName, const std::string & entries)\fC [static]\fP"
.PP
\fBTodo\fP
.RS 4
This function should be used to distribute all table header creations to their classes. 
.RE
.PP

.SS "virtual void vjassdoc::Object::init ()\fC [pure virtual]\fP"
.PP
Implemented in \fBvjassdoc::Comment\fP, \fBvjassdoc::DocComment\fP, \fBvjassdoc::Function\fP, \fBvjassdoc::FunctionInterface\fP, \fBvjassdoc::Global\fP, \fBvjassdoc::Interface\fP, \fBvjassdoc::Keyword\fP, \fBvjassdoc::Library\fP, \fBvjassdoc::Member\fP, \fBvjassdoc::Method\fP, \fBvjassdoc::Scope\fP, \fBvjassdoc::SourceFile\fP, \fBvjassdoc::Struct\fP, \fBvjassdoc::TextMacro\fP, \fBvjassdoc::TextMacroInstance\fP, and \fBvjassdoc::Type\fP.
.SS "virtual void vjassdoc::Object::pageNavigation (std::ofstream & file) const\fC [pure virtual]\fP"
.PP
Implemented in \fBvjassdoc::Comment\fP, \fBvjassdoc::DocComment\fP, \fBvjassdoc::Function\fP, \fBvjassdoc::FunctionInterface\fP, \fBvjassdoc::Global\fP, \fBvjassdoc::Interface\fP, \fBvjassdoc::Keyword\fP, \fBvjassdoc::Library\fP, \fBvjassdoc::Member\fP, \fBvjassdoc::Method\fP, \fBvjassdoc::Scope\fP, \fBvjassdoc::SourceFile\fP, \fBvjassdoc::Struct\fP, \fBvjassdoc::TextMacro\fP, \fBvjassdoc::TextMacroInstance\fP, and \fBvjassdoc::Type\fP.
.SS "virtual void vjassdoc::Object::page (std::ofstream & file) const\fC [pure virtual]\fP"
.PP
Implemented in \fBvjassdoc::Comment\fP, \fBvjassdoc::DocComment\fP, \fBvjassdoc::Function\fP, \fBvjassdoc::FunctionInterface\fP, \fBvjassdoc::Global\fP, \fBvjassdoc::Interface\fP, \fBvjassdoc::Keyword\fP, \fBvjassdoc::Library\fP, \fBvjassdoc::Member\fP, \fBvjassdoc::Method\fP, \fBvjassdoc::Scope\fP, \fBvjassdoc::SourceFile\fP, \fBvjassdoc::Struct\fP, \fBvjassdoc::TextMacro\fP, \fBvjassdoc::TextMacroInstance\fP, and \fBvjassdoc::Type\fP.
.SS "std::string vjassdoc::Object::pageLink () const\fC [inline]\fP"
.PP
.SS "std::string vjassdoc::Object::sqlStatement () const\fC [virtual]\fP"
.PP
Reimplemented in \fBvjassdoc::DocComment\fP, \fBvjassdoc::Function\fP, \fBvjassdoc::FunctionInterface\fP, \fBvjassdoc::Global\fP, \fBvjassdoc::Interface\fP, \fBvjassdoc::Keyword\fP, \fBvjassdoc::Library\fP, \fBvjassdoc::Member\fP, \fBvjassdoc::Method\fP, \fBvjassdoc::Scope\fP, \fBvjassdoc::SourceFile\fP, \fBvjassdoc::Struct\fP, \fBvjassdoc::TextMacro\fP, \fBvjassdoc::TextMacroInstance\fP, and \fBvjassdoc::Type\fP.
.SS "unsigned int vjassdoc::Object::id () const\fC [inline]\fP"
.PP
.SS "void vjassdoc::Object::addIdentifier (const std::string & identifier)\fC [inline]\fP"
.PP
.SS "std::string vjassdoc::Object::identifier () const\fC [inline]\fP"
.PP
.SS "class \fBSourceFile\fP * vjassdoc::Object::sourceFile () const\fC [inline]\fP"
.PP
.SS "unsigned int vjassdoc::Object::line () const\fC [inline]\fP"
.PP
.SS "class \fBDocComment\fP * vjassdoc::Object::docComment () const\fC [inline]\fP"
.PP
.SS "class \fBObject\fP * vjassdoc::Object::container () const\fC [virtual]\fP"
.PP
Reimplemented in \fBvjassdoc::Member\fP, and \fBvjassdoc::Method\fP.
.SS "class \fBScope\fP * vjassdoc::Object::scope () const\fC [virtual]\fP"
.PP
Reimplemented in \fBvjassdoc::FunctionInterface\fP, \fBvjassdoc::Global\fP, \fBvjassdoc::Interface\fP, and \fBvjassdoc::Keyword\fP.
.SS "class \fBLibrary\fP * vjassdoc::Object::library () const\fC [virtual]\fP"
.PP
Reimplemented in \fBvjassdoc::FunctionInterface\fP, \fBvjassdoc::Global\fP, \fBvjassdoc::Interface\fP, \fBvjassdoc::Keyword\fP, and \fBvjassdoc::Scope\fP.
.SS "bool vjassdoc::Object::hasToSearchValueObject (class \fBObject\fP * type, const std::string & expression)\fC [static, protected]\fP"
.PP
Checks if the value 
.PP
\fBParameters:\fP
.RS 4
\fIexpression\fP which has type 
.br
\fItype\fP is a literal or not. If it is no literal method will return true. 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
Code type == null?! 
.RE
.PP

.SS "std::string vjassdoc::Object::showBooleanProperty (const bool & property)\fC [inline, static, protected]\fP"
.PP
Shows a boolean value. This method has been written for showing boolean members of classes in a HTML file. Instead of 0 and 1 it returns the strings 'No' and 'Yes' in the local language. 
.SS "void vjassdoc::Object::setIdentifier (const std::string & identifier)\fC [inline, protected]\fP"
.PP
.SS "std::string vjassdoc::Object::anchor () const\fC [inline, protected]\fP"
.PP
.SS "class \fBObject\fP * vjassdoc::Object::searchObjectInList (const std::string & identifier, const enum \fBParser::List\fP & list, enum \fBParser::SearchMode\fP searchMode = \fCParser::Unspecified\fP)\fC [inline, protected]\fP"
.PP
.SS "class \fBObject\fP * vjassdoc::Object::findValue (class \fBObject\fP * type, std::string & valueExpression)\fC [protected]\fP"
.PP
Checks if 
.PP
\fBParameters:\fP
.RS 4
\fIvalueExpression\fP is a literal or an object. If it's an object (like a global or function call) it will be searched in parser lists. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "class \fBObject\fP* \fBvjassdoc::Object::m_container\fP\fC [protected]\fP"
.PP
.SS "class \fBScope\fP* \fBvjassdoc::Object::m_scope\fP\fC [protected]\fP"
.PP
.SS "class \fBLibrary\fP* \fBvjassdoc::Object::m_library\fP\fC [protected]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
