.TH "vjassdoc::Global::Size" 3 "7 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::Global::Size \- 
.SH SYNOPSIS
.br
.PP
\fC#include <global.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSize\fP (unsigned int size)"
.br
.ti -1c
.RI "\fBSize\fP (class \fBObject\fP *size)"
.br
.ti -1c
.RI "unsigned int \fBtoUint\fP () const "
.br
.ti -1c
.RI "class \fBObject\fP * \fBtoObject\fP () const "
.br
.RI "\fI* inline */ \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vjassdoc::Global::Size::Size (unsigned int size)"
.PP
.SS "vjassdoc::Global::Size::Size (class \fBObject\fP * size)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "unsigned int vjassdoc::Global::Size::toUint () const"
.PP
.SS "class \fBObject\fP* vjassdoc::Global::Size::toObject () const"
.PP
* inline */ 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
