.TH "vjassdoc::Struct" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::Struct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <struct.h>\fP
.PP
Inherits \fBvjassdoc::Interface\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStruct\fP (const std::string &identifier, class \fBSourceFile\fP *sourceFile, unsigned int line, class \fBDocComment\fP *docComment, class \fBLibrary\fP *library, \fBScope\fP *scope, bool isPrivate, const std::string &extensionExpression)"
.br
.ti -1c
.RI "\fBStruct\fP (std::vector< const unsigned char * > &columnVector)"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()"
.br
.ti -1c
.RI "virtual void \fBpageNavigation\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual void \fBpage\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual std::string \fBsqlStatement\fP () const "
.br
.ti -1c
.RI "class \fBInterface\fP * \fBextension\fP () const "
.br
.ti -1c
.RI "class \fBMethod\fP * \fBconstructor\fP () const "
.br
.ti -1c
.RI "class \fBMethod\fP * \fBdestructor\fP () const "
.br
.ti -1c
.RI "class \fBMethod\fP * \fBinitializer\fP () const "
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBHasExtension\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vjassdoc::Struct::Struct (const std::string & identifier, class \fBSourceFile\fP * sourceFile, unsigned int line, class \fBDocComment\fP * docComment, class \fBLibrary\fP * library, \fBScope\fP * scope, bool isPrivate, const std::string & extensionExpression)"
.PP
.SS "vjassdoc::Struct::Struct (std::vector< const unsigned char * > & columnVector)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void vjassdoc::Struct::init ()\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Interface\fP.
.SS "void vjassdoc::Struct::pageNavigation (std::ofstream & file) const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Interface\fP.
.SS "void vjassdoc::Struct::page (std::ofstream & file) const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Interface\fP.
.SS "std::string vjassdoc::Struct::sqlStatement () const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Interface\fP.
.SS "class \fBInterface\fP * vjassdoc::Struct::extension () const\fC [inline]\fP"
.PP
.SS "class \fBMethod\fP * vjassdoc::Struct::constructor () const\fC [inline]\fP"
.PP
.SS "class \fBMethod\fP * vjassdoc::Struct::destructor () const\fC [inline]\fP"
.PP
.SS "class \fBMethod\fP * vjassdoc::Struct::initializer () const\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
