.TH "vjassdoc::Global" 3 "9 Mar 2009" "Version 0.2.3" "vjassdoc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vjassdoc::Global \- 
.SH SYNOPSIS
.br
.PP
\fC#include <global.h>\fP
.PP
Inherits \fBvjassdoc::Object\fP.
.PP
Inherited by \fBvjassdoc::Member\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlobal\fP (const std::string &identifier, class \fBSourceFile\fP *sourceFile, unsigned int line, class \fBDocComment\fP *docComment, class \fBLibrary\fP *library, class \fBScope\fP *scope, bool isPrivate, bool isPublic, bool isConstant, const std::string &typeExpression, const std::string &valueExpression, const std::string &sizeExpression)"
.br
.ti -1c
.RI "\fBGlobal\fP (std::vector< const unsigned char * > &columnVector)"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()"
.br
.ti -1c
.RI "virtual void \fBpageNavigation\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual void \fBpage\fP (std::ofstream &file) const "
.br
.ti -1c
.RI "virtual std::string \fBsqlStatement\fP () const "
.br
.ti -1c
.RI "virtual class \fBLibrary\fP * \fBlibrary\fP () const "
.br
.ti -1c
.RI "virtual class \fBScope\fP * \fBscope\fP () const "
.br
.ti -1c
.RI "bool \fBisPrivate\fP () const "
.br
.ti -1c
.RI "bool \fBisPublic\fP () const "
.br
.ti -1c
.RI "bool \fBisConstant\fP () const "
.br
.ti -1c
.RI "class \fBObject\fP * \fBtype\fP () const "
.br
.ti -1c
.RI "std::string \fBtypeExpression\fP () const "
.br
.ti -1c
.RI "class \fBObject\fP * \fBvalue\fP () const "
.br
.ti -1c
.RI "std::string \fBvalueLiteral\fP () const "
.br
.ti -1c
.RI "class \fBObject\fP * \fBsize\fP () const "
.br
.ti -1c
.RI "int \fBsizeLiteral\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vjassdoc::Global::Global (const std::string & identifier, class \fBSourceFile\fP * sourceFile, unsigned int line, class \fBDocComment\fP * docComment, class \fBLibrary\fP * library, class \fBScope\fP * scope, bool isPrivate, bool isPublic, bool isConstant, const std::string & typeExpression, const std::string & valueExpression, const std::string & sizeExpression)"
.PP
.SS "vjassdoc::Global::Global (std::vector< const unsigned char * > & columnVector)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void vjassdoc::Global::init ()\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.PP
Reimplemented in \fBvjassdoc::Member\fP.
.SS "void vjassdoc::Global::pageNavigation (std::ofstream & file) const\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.PP
Reimplemented in \fBvjassdoc::Member\fP.
.SS "void vjassdoc::Global::page (std::ofstream & file) const\fC [virtual]\fP"
.PP
Implements \fBvjassdoc::Object\fP.
.PP
Reimplemented in \fBvjassdoc::Member\fP.
.SS "std::string vjassdoc::Global::sqlStatement () const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Object\fP.
.PP
Reimplemented in \fBvjassdoc::Member\fP.
.SS "class \fBLibrary\fP * vjassdoc::Global::library () const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Object\fP.
.SS "class \fBScope\fP * vjassdoc::Global::scope () const\fC [virtual]\fP"
.PP
Reimplemented from \fBvjassdoc::Object\fP.
.SS "bool vjassdoc::Global::isPrivate () const\fC [inline]\fP"
.PP
.SS "bool vjassdoc::Global::isPublic () const\fC [inline]\fP"
.PP
.SS "bool vjassdoc::Global::isConstant () const\fC [inline]\fP"
.PP
.SS "class \fBObject\fP * vjassdoc::Global::type () const\fC [inline]\fP"
.PP
.SS "std::string vjassdoc::Global::typeExpression () const\fC [inline]\fP"
.PP
.SS "class \fBObject\fP * vjassdoc::Global::value () const\fC [inline]\fP"
.PP
.SS "std::string vjassdoc::Global::valueLiteral () const\fC [inline]\fP"
.PP
.SS "class \fBObject\fP * vjassdoc::Global::size () const\fC [inline]\fP"
.PP
.SS "int vjassdoc::Global::sizeLiteral () const\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for vjassdoc from the source code.
