# This spec file was generated by KDevelop 
# Please report any problem to KDevelop Team <kdevelop-devel@kdevelop.org> 
# Thanks to Matthias Saou for his explanations on http://freshrpms.net/docs/fight.html

Name: vjassdoc
Version: 0.3
Release: 1
Vendor: Tamino Dauth <tamino@cdauth.de>
License: GPLv2
Summary: A simple Jass and vJass documentation generation tool.
Group: Development/Tools
Packager: Tamino Dauth
BuildRoot: %{_tmppath}/%{name}-root
Source: http://cdauth.de/~tamino/vjasssdk/vjassdoc/releases/vjassdoc-0.2.3.tar.bz2
#Icon: images/vjassdoc.xpm
URL: http://cdauth.de/~tamino/vjasssdk/vjassdoc/
Requires: sqlite >= 3.6.13

%description
A simple Jass and vJass documentation generation tool written in C++.
Is able to generate HTML files and SQLite3 databases.



%prep
%setup
cmake %{buildroot}

%build
%configure
make

%install
rm -rf %{buildroot}
%makeinstall

%clean
rm -rf %{buildroot}

%post -p /sbin/ldconfig
%postun -p /sbin/ldconfig
%files
%defattr(-, root, root)
%doc AUTHORS COPYING ChangeLog NEWS README TODO
%{_bindir}/*
%{_libdir}/*.so.*
%{_datadir}/%{name}
%{_mandir}/man8/*
%changelog


